#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=
#
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/v1/products/**
#
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/v1/orders/**,/v1/cart/**
#
#            - id: eureka-server
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/main
#              filters:
#                - SetPath=/
#            - id: eureka-server-static
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO


